#!/bin/bash

docker network create test

docker build -t test-php . --build-arg INSTALL_XDEBUG=false --build-arg INSTALL_OPCACHE=false --file=$TRAVIS_BUILD_DIR/.docker/php/Dockerfile
docker build -t test-nginx . --file=$TRAVIS_BUILD_DIR/.docker/nginx/Dockerfile
docker build -t test-mysql . --file=$TRAVIS_BUILD_DIR/.docker/mysql/Dockerfile

docker run --name test-mysql  --net test -e MYSQL_ROOT_PASSWORD=root -e MYSQL_USER=test -e MYSQL_PASSWORD=test -e MYSQL_DATABASE=test -d -t test-mysql
#This is temporary fix. We need to move to a docker-compose
sleep 5
docker run --name test-php --net test -v $TRAVIS_BUILD_DIR:/var/www --env DB_HOST=test-mysql -d -t test-php
sleep 5
docker run --name test-nginx --net test -v $TRAVIS_BUILD_DIR:/var/www -d -t test-nginx
sleep 5
docker exec test-php composer install
docker exec test-php cp .env.example .env
docker exec test-php sed -i '/DB_HOST/c\DB_HOST=test-mysql' .env
docker exec test-php sed -i '/DB_DATABASE/c\DB_DATABASE=test' .env
docker exec test-php sed -i '/DB_USERNAME/c\DB_USERNAME=test' .env
docker exec test-php sed -i '/DB_PASSWORD/c\DB_PASSWORD=test' .env
docker exec test-php php artisan key:generate
docker exec test-php php artisan migrate
docker exec test-php php artisan migrate:rollback
docker exec test-php php artisan migrate:fresh

docker stop test-nginx
docker stop test-php
docker stop test-mysql
docker rm test-nginx
docker rm test-php
docker rm test-mysql
docker rmi test-mysql
docker rmi test-nginx
docker rmi test-php
docker network rm test